name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker
        run: |
          rm -rf dist
          docker build --no-cache --rm --tag tmaize/apisix-acme:${{ github.ref_name }} .
          docker push tmaize/apisix-acme:${{ github.ref_name }}
